### PR TITLE
make missing @kcfg_path self-documenting

### PR DESCRIPTION
**Pull request by grosser**
@cben

### CODE REVIEW

**Comment by grosser** [comment]
also I'd propose to change readme to only reference `.read` 🤷

**Comment by grosser** [comment]
also I'd propose to change readme to only reference `.read` 🤷

**Comment by cben** [comment]
> also I'd propose to change readme to only reference .read 🤷

I'm fine with emphasizing .read, but I believe a library should offer the _ability_ do work on passed-in data with no connection to the file system.

But note the exception you're raising only refers to .new - thats a fine place to mention only .read (using constructor directly but with file path is really niche...)

**Comment by cben** [comment]
Good to merge as-is if you want.

**Comment by grosser** [comment]
yeah just merge :)

**Pull request merged**
