### PR TITLE
Added automatic inclusion of object kind and api version for create requ...

### PR DESCRIPTION
**Pull request by stephenjlevy**
Creating entities was failing because the spec requires the entity kind and apiversion.  Added code to automatically include these fields.

### CODE REVIEW

**Comment by abonas** [comment]
@stephenjlevy thanks for the PR.
What error were you getting from the server prior to the fix?
I assume it is relevant to this issue?
https://github.com/GoogleCloudPlatform/kubernetes/issues/3000

**Comment by stephenjlevy** [comment]
@abonas I assumed that the "kind" field was being automatically included since the request knew the entity type, but it wasn't.  I was seeing the following error when trying to start a service without specifying "kind": "Service" or the api version.

`/usr/local/lib/ruby/gems/2.0.0/gems/kubeclient-0.1.8/lib/kubeclient/common.rb:15:in `rescue in handle_exception': Service "" is invalid: [metadata.name: required value, spec.port: invalid value '0': must be greater than 0 and less than 65536, spec.protocol: required value, spec.sessionAffinity: required value] (KubeException)`

**Comment by abonas** [comment]
> @abonas I assumed that the "kind" field was being automatically included since the request knew the entity type, but it wasn't. I was seeing the following error when trying to start a service without specifying "kind": "Service" or the api version.
> 
> /usr/local/lib/ruby/gems/2.0.0/gems/kubeclient-0.1.8/lib/kubeclient/common.rb:15:inrescue in handle_exception': Service "" is invalid: metadata.name: required value, spec.port: invalid value '0': must be greater than 0 and less than 65536, spec.protocol: required value, spec.sessionAffinity: required value`

afaik both kind and api version are filled automatically by server side.
I tried to create for example a namespace without specifying them and the request succeeds.

{
"metadata": {
"name": "staging"
},
"spec": {},
"labels": {
"name": "staging"
}
}

It seems that there were other fields that were missing in your example based on the message that you pasted above - name, port, protocol and sessionAffinity. Can you post the example json /how do you construct the service object?

**Comment by abonas** [comment]
@stephenjlevy  I think I might understand now what you're experiencing, I opened a question regarding it, please see here, lets follow the responses there and based on that see if your PR needs to be merged or not.
https://github.com/GoogleCloudPlatform/kubernetes/issues/6439

**Comment by abonas** [comment]
@stephenjlevy , please add a comment in code that those additions are needed till GoogleCloudPlatform/kubernetes#6439 is resolved, and I'll merge the PR.

**Comment by stephenjlevy** [comment]
Travis is failing on new regular expression checking in upstream code that was just added to rubocop 0.30.0 (released earlier today).  The failures are not in code related to this PL.

**Comment by abonas** [comment]
@stephenjlevy , I fixed that here:
https://github.com/abonas/kubeclient/pull/62
you can rebase.
I am going to limit rubocop version for future to gain more control over it.

**Comment by stephenjlevy** [comment]
@abonas I have rebased

**Pull request merged**
