### PR TITLE
parallelize rubocop and normal tests for speed and clarity on what broke

### PR DESCRIPTION
**Pull request by grosser**
@abonas

### CODE REVIEW

**Comment by grosser** [comment]
screen shot 2016-05-01 at 10 38 23 am

**Comment by grosser** [comment]
(test errors are fixed with https://github.com/abonas/kubeclient/pull/165)

**Comment by grosser** [comment]
@abonas rebased this one ... should be green now

**Comment by abonas** [comment]
how much time does this save? the gem's tests shouldn't take too long to run in the first place.
cc @simon3z

**Comment by grosser** [comment]
takes it from 45s to 30s for ruby 2.0-2.2 ... but I think the main win is visibility, it's now obvious that rubocop failed and not the tests itself

**Comment by abonas** [comment]
I don't have any objections/concerns regarding this change.
@simon3z wdyt?

**Comment by simon3z** [comment]
I am definitely in favor of the `.travis.yml` file change.
On the other hand I don't think we need the complexity introduced in `Rakefile` (but don't block on me for this one).

**Comment by abonas** [comment]
@simon3z yes, I also had thoughts about the Rakefile.

**Comment by grosser** [comment]
updated Rakefile

**Pull request merged**
