### PR TITLE
merge Common into kubeclient to simplify setup

### PR DESCRIPTION
**Pull request by grosser**
fixes https://github.com/abonas/kubeclient/issues/492#issuecomment-808019835
@cben 

... after this is merged some cleanup to make methods private would be good

### CODE REVIEW

**Comment by cben** [comment]
Thanks!  I merged some other PRs so has conflicts now.

**Comment by grosser** [comment]
rebased

**Comment by cben** [comment]
truffleruby failed:
```
  1) Failure:
RetryTest#test_watches_for_add [/home/runner/work/kubeclient/kubeclient/test/test_informer.rb:61]:
Expected: ["a", "b"]
  Actual: ["a"]
```
Sounds like issues you recently fixed https://github.com/abonas/kubeclient/pull/494#issuecomment-808960866?

**Comment by grosser** [comment]
yeah, I think it's a race condition in the test ... let me restart the test to see if it goes away, can fix the test in another PR

**Comment by grosser** [comment]
... it keeps happening on truffle ruby, but always a different test-case, so skipped informer test for truffle-ruby until I have time to do a more reliable fix for it

**Comment by grosser** [comment]
all good now 👍

**Pull request merged**
