### PR TITLE
Bump version to 2.0.0

### PR DESCRIPTION
**Pull request by simon3z**
cc @abonas @jonmoter @zeari @yaacov @cben @grosser @zakiva @moolitayer

### CODE REVIEW

**Comment by zakiva** [comment]
I think we are still missing the option to set the target API of the client, @moolitayer have you added it already?

**Comment by moolitayer** [comment]
> I think we are still missing the option to set the target API of the client, @moolitayer have you added it already?

The idea was instead of having to recreate the client to change groups to have a method that would
set group & version. That would have to reset discovery & delete defined methods.

cc @zeari @simon3z

**Comment by zeari** [comment]
ping @simon3z

**Comment by simon3z** [comment]
> ping @simon3z

@zeari I discussed this with @moolitayer and @zakiva this morning. Waiting here for either +1's or other PRs before proceeding.

**Comment by moolitayer** [comment]
LGTM :+1: 
Discussed with @zakiva how ManageIQ code should look

**Comment by simon3z** [comment]
Released: https://rubygems.org/gems/kubeclient/versions/2.0.0

**Pull request merged**
