### PR TITLE
allow setting default :as for the whole client

### PR DESCRIPTION
**Pull request by grosser**
also passes all replies through format_response which will allow for easy addition of a new
:as type, I'm plaing to use `JSON.parse(value, symbolize_names: true)`

### CODE REVIEW

**Comment by cben** [comment]
Didn't review in detail but looks pretty good!
Some ideas, not sure if helping or overkill:

Consider making WatchStream too ask the client to format notices, so overriding `format_response` would affect it too.  (May becomes better to split it into 3 methods rather than one returning 3 types depending on args.)

I've thought about letting :as param take an object, that's expected to have a method (or 3) implementing conversion of responses.
There would be a helper mapping :raw and :ros symbols into 2 such builtin objects; but any other object is possible.

**Comment by grosser** [comment]
updated ... trying to keep this change as small as possible :D
looks good ?

**Comment by cben** [comment]
LGTM :+1:  @enoodle can you review as well?

@grosser can you document this in README?

**Comment by cben** [comment]
Merging; @grosser please either send followup to document this in README & CHANGELOG, or nag me to do it.

**Pull request merged**
