### PR TITLE
Added ConfigMap to entity types

### PR DESCRIPTION
**Pull request by zeari**
Kubernetes config maps described here:  http://kubernetes.io/docs/user-guide/configmap/

### CODE REVIEW

**Comment by zeari** [comment]
@abonas Which tests are expected to be added here?

**Comment by abonas** [comment]
@simon3z I am not aware of this feature/requirement, I guess you should have more background on this. Please answer @zeari question re testing.

**Comment by simon3z** [comment]
@abonas @zeari I am not aware of this requirement being currently evaluated.

For testing, I think we'll have to add a `test_config_map.rb` as for the rest of the entities.

Anyway until this is not fixed:

```
Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
```

We won't be able to merge anything (unless we overrule the travis).

**Comment by abonas** [comment]
So why is this frature needed if noone is aware of it at the moment? :)

**Comment by jonmoter** [comment]
I'm in favor of having kubeclient support all the entity types that are available in the Kubernetes API. We use ConfigMaps minimally, but I could see using them more in the future.

**Comment by zeari** [comment]
> I'm in favor of having kubeclient support all the entity types that are available in the Kubernetes API.

Thats pretty much it is. There was a missing entity and i thought id add it...

**Comment by simon3z** [comment]
> Thats pretty much what it is. There was a missing entity and i thought id add it...

@zeari yes but IIUC what @moolitayer is working on in #144 is covering these additional entities automatically. Unless we need ConfigMaps ASAP, the switch to the new group API seems a more interesting investment going forward.

What instead is really urgent to fix (cc @jonmoter) is the current failure we have with activesupport requiring Ruby version >= 2.2.2, which is blocking all the PR going forward.

I pinpointed this to be an issue related to rubygems 2.4.5 (with rubygems 2.4.8 the required ruby version is taken in account), but anyway travis only has rubygems 2.4.5.

We'll probably need a workaround for that in our gemspec for the time being.

**Comment by moolitayer** [comment]
@zeari fyi you test config maps on #181:
```
client = Kubeclient::Client.new 'http://localhost:8080/api' , 'v1', ssl_options: ssl_options
client.get_config_maps
```

**Comment by zeari** [comment]
Closing in favor of #181

**Pull request closed without merging**
