### PR TITLE
Updated changelog on master to list 2.5.2 release

### PR DESCRIPTION
**Pull request by cben**

### CODE REVIEW

**Comment by cben** [comment]
@jhernand please review, we just did a 2.5.2 release: #287, #301, #302, #303. The 2.x branch CHANELOG is https://github.com/abonas/kubeclient/blob/v2.x/CHANGELOG.md

**Comment by cben** [comment]
Also corrected 3.0.0 release date (wrote original changelog expecting to release on Thu, actually released on Sunday)

@abonas @simon3z I'd like to avoid merging my PRs in Mooli's absence.

**Comment by simon3z** [comment]
> @abonas @simon3z I'd like to avoid merging my PRs in Mooli's absence.

@cben if it's just text I don't see any harm

**Comment by cben** [comment]
>
> @cben <https://github.com/cben> if it's just text I don't see any harm
>
I didn't see any harm either, which is exactly the slippery slope / bad
habit I don't want to develop ;-)

**Comment by simon3z** [comment]
> I didn't see any harm either, which is exactly the slippery slope / bad
> habit I don't want to develop ;-)

@cben you had a review/approval by jhernand, 2 engineers on a changelog text is enough, the important part is the review process not who is merging.

**Pull request merged**
