### PR TITLE
Add content-type header = application/json for create and update actions

### PR DESCRIPTION
**Pull request by simon3z**
Following PR  Split codec from scheme #17922 on k8s server.

### CODE REVIEW

**Comment by simon3z** [comment]
@abonas this is a serious issue (backported from master) that we want to fix in v0.8.z releasing a v0.8.1.

**Comment by abonas** [comment]
> @abonas this is a serious issue (backported from master) that we want to fix in v0.8.z releasing a v0.8.1.

what is the reason for the need in 0.8.z and not taking the last gem release containing the fix?
btw did you check the watches area? perhaps it is of a need in a similar fix too (I saw briefly someone commenting on content type and watches in the k8s side of things)

**Comment by simon3z** [comment]
> what is the reason for the need in 0.8.z and not taking the last gem release containing the fix?

@abonas because between v0.8.0 and v1.1.1 there are 654 insertions and 96 deletions spread over 17 files. Also, the new dependency on `recursive-open-struct = 1.0.0` and the new `http` gem.

You don't want to bring all those changes to applications that are already in production and they just need this fix.

**Comment by abonas** [comment]
agreed, you have my blessing :)

**Pull request merged**
