### PR TITLE
Add Ruby 2.3 to .travis.yml

### PR DESCRIPTION
**Pull request by abonas**

### CODE REVIEW

**Comment by abonas** [comment]
Pending resolution for https://github.com/travis-ci/travis-ci/issues/5361#issuecomment-167517718

**Comment by abonas** [comment]
@jrafanie please see correspondence here https://github.com/travis-ci/travis-ci/issues/5361#issuecomment-167517718
how would you suggest to proceed? will you add 2.3.0 to miq travis or wait till resolving 2.3 will be done?

**Comment by jrafanie** [comment]
We'll have to use 2.3.0 in the .travis.yml here and in miq until they update the build environment.

**Comment by abonas** [comment]
> We'll have to use 2.3.0 in the .travis.yml here and in miq until they update the build environment.

that's possible, I was just wondering how urgent this is for miq in regards of waiting till 2.3 is sorted to keep the naming alignment.

**Pull request merged**
