### PR TITLE
common: add support for the ca cert_store

### PR DESCRIPTION
**Pull request by simon3z**
This patch adds the support for the cert_store as an alternative to the ca_file.

### CODE REVIEW

**Comment by abonas** [comment]
@simon3z please rebase

**Comment by abonas** [comment]
How does this behave when passing both the ca_file and the store?

**Comment by simon3z** [comment]
> How does this behave when passing both the ca_file and the store?

It uses the same semantic of `net/http` and `OpenSSL`, we're not doing anything with it.

https://github.com/ruby/ruby/blob/v2_2_0/ext/openssl/ossl_ssl.c#L693-L704
https://github.com/ruby/ruby/blob/v2_2_0/ext/openssl/ossl_ssl.c#L750-L757
https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_load_verify_locations.html

(the semantic is to consider them all, `cert_store`, `ca_file` and `ca_path`)

**Comment by abonas** [comment]
LGTM

**Pull request merged**
