### PR TITLE
convert to github actions

### PR DESCRIPTION
**Pull request by grosser**
travis is getting slow, so replace it 🤷

### CODE REVIEW

**Comment by grosser** [comment]
@cben plz enable GA for this repo so I can test this

**Comment by cben** [comment]
Sorry for being non-responsive again.
This is actually not my repo, @abonas can you check whether github actions are disabled?

But docs say they are enabled by default in all repos.  I tried this on my fork, without having to enable anything. It showed me they're enabled in my fork:
Ekrankopio de 2020-11-13 08-21-14
and while my PR Checks tab (https://github.com/cben/kubeclient/pull/1/checks) had confusing "Waiting for checks information..." status, I merged it into my master and now I see Actions there:
https://github.com/cben/kubeclient/actions

@grosser how about you keep .travis.yml for now, and I'll just merge this and we'll see?

P.S. 3 tests are [failing on master :red_circle:](https://travis-ci.org/github/abonas/kubeclient), going back a few commits doesn't help, possibly some dependency changed?  Investigating...

**Comment by grosser** [comment]
then let's merge https://github.com/abonas/kubeclient/pull/475 and I'll rebase this PR if it works

**Comment by grosser** [comment]
all good!

**Comment by grosser** [comment]
@cben good to go ?

**Pull request merged**
