### PR TITLE
Add service account entity

### PR DESCRIPTION
**Pull request by simon3z**
This pull request adds the support for the `service accounts` and the `security context constraints` entities.

### CODE REVIEW

**Comment by simon3z** [comment]
cc @abonas

**Comment by abonas** [comment]
Is SecurityContextConstraint a k8s feature or OpenShift feature? I don't see it in k8s docs/api reference

**Comment by jimmidyson** [comment]
OpenShift only atm, although at some point I believe they are hoping to merge it upstream.

**Comment by abonas** [comment]
> OpenShift only atm, although at some point I believe they are hoping to merge it upstream.

thanks @jimmidyson . so if that's the case, this entity should be added at https://github.com/abonas/openshift_client and not here

**Comment by simon3z** [comment]
@deads2k how come `/api/v1/securitycontextconstraints` in OpenShift is exposed as a Kubernetes api? (Instead of `/oapi`) Is it an exception? are there other exceptions as this one?

**Comment by deads2k** [comment]
> @deads2k how come /api/v1/securitycontextconstraints in OpenShift is exposed as a Kubernetes api? (Instead of /oapi) Is it an exception? are there other exceptions as this one?

We were trying to get it merged upstream before 3.0.  We thought it was going to make it in, but it never did.  In order to support backwards compatibility, we've been carrying it ever since.

There aren't any other entire types that are under `/api`, but only exist in origin.  However, we do run ahead on some security related features, so some we have a few extra fields on certain types.  The swagger for whatever server you're talking to should be up to date.

Kube has also added some resource discovery APIs.  I'll try to look up examples today.  If I forget, remind me tomorrow.

**Comment by simon3z** [comment]
Thanks @deads2k I remember you warned us about it, but I thought backward compatibility was only about the body of the entities.

**Pull request merged**
