### PR TITLE
add a changelog

### PR DESCRIPTION
**Pull request by abonas**

### CODE REVIEW

**Comment by abonas** [comment]
@simon3z fyi

**Comment by simon3z** [comment]
@abonas how should we maintain this? Can you document the procedure to get it generated? Thanks.

**Comment by abonas** [comment]
@simon3z the manual way is rather simple:
gem install github_changelog_generator
and then:
https://github.com/skywinder/Github-Changelog-Generator#usage
(check there the note regarding the token needed to increase num of requests to github)
I do think it should be automatically generated, still haven't reached a conclusion where it's best to be added.
Opened https://github.com/abonas/kubeclient/issues/112 to track it.

**Comment by abonas** [comment]
not relevant anymore as newer gems were released

**Pull request closed without merging**
