### PR TITLE
lock down webmock to pass tests

### PR DESCRIPTION
**Pull request by grosser**
@abonas CI is broken / and tests fail locally :(

### CODE REVIEW

**Comment by grosser** [comment]
should have checked in that Gemfile.lock :(

**Comment by grosser** [comment]
stole working versions from https://travis-ci.org/abonas/kubeclient/jobs/120659814 and narrowed it down to the webmock upgrade ...

**Comment by simon3z** [comment]
Thanks @grosser :+1: . Why the extra (empty) patch? You could probably squash them.

**Comment by abonas** [comment]
@grosser thank you for your contribution! as @simon3z suggests, please remove the empty patch and change the PR title to a more clear one. thanks!

**Comment by grosser** [comment]
updated

**Comment by grosser** [comment]
good to go @abonas ?

**Pull request merged**
