### PR TITLE
Ensure dynamic classes live in the Kubeclient namespace.

### PR DESCRIPTION
**Pull request by Fryguy**
@abonas Please review.

### CODE REVIEW

**Comment by Fryguy** [comment]
Technically #29 implemented the dynamic classes properly, since the original classes were not namespaced.  However, a gem *should* namespace its own classes.

**Comment by abonas** [comment]
@Fryguy looks great to me, thanks a lot for the patch. 
Just a small question - is it OK not mentioning the module name when accessing ENTITY_TYPES inside Kubeclient class, now that it moved out of the class? I know it works, but is it a good/safe practice?

I think rubocop found a minor thing, pls fix it so it will pass.

**Comment by Fryguy** [comment]
Do you have any suggestions for the module comment...I was thinking of just taking what's in the README.  Incidentally, I think a round of documentation might be a good idea at some point...would help flesh out http://www.rubydoc.info/gems/kubeclient

**Comment by Fryguy** [comment]
> Just a small question - is it OK not mentioning the module name when accessing ENTITY_TYPES inside Kubeclient class, now that it moved out of the class? I know it works, but is it a good/safe practice?

Yes it is fine.  It is accessible by scope, so it works, and it is not uncommon to do it this way.

**Comment by Fryguy** [comment]
well that's weird...I updated the comment and the tests are now failing?!  even locally that happens...I think the rakefile needs an update...I'll do that in a separate PR.

For now, I'll try to make the tests pass here.

**Comment by abonas** [comment]
> Do you have any suggestions for the module comment...I was thinking of just taking what's in the README. Incidentally, I think a round of documentation might be a good idea at some point...would help flesh out http://www.rubydoc.info/gems/kubeclient

I'm always pro documentation, what do you have in mind/ what did you mean by fleshing out http://www.rubydoc.info/gems/kubeclient? README is detailed enough, no? unless I misunderstood you.

**Comment by Fryguy** [comment]
Well, documentation at the class level and method level would be helpful to people reading the code.  rubydoc.info reads those docs and generates nice pages.

**Comment by abonas** [comment]
> Well, documentation at the class level and method level would be helpful to people reading the code. rubydoc.info reads those docs and generates nice pages.

yes, sure, any reference to a good example/convention of doing that?
are you planning to fix this current PR so it can be merged?

**Comment by Fryguy** [comment]
Yeah working on it... The are a lot of namespacing oddities it turns out.

**Comment by abonas** [comment]
> Yeah working on it... The are a lot of namespacing oddities it turns out.
> …

ok, pls share when you understand what's going on there :)

**Comment by Fryguy** [comment]
Closing in favor on #39

**Pull request closed without merging**
