### PR TITLE
raise KeyError as .fetch would do to behave more intuitive

### PR DESCRIPTION
**Pull request by grosser**
I want to show an error message when a user asks for an unknown context, so catching a KeyError would be much nicer than RuntimeError ... also seem like the correct exception to me when it basically behaves like a .fetch

### CODE REVIEW

**Comment by simon3z** [comment]
LGTM :+1: 
@moolitayer can you review?

**Comment by simon3z** [comment]
@grosser it seems that Travis is failing and it has some troubles displaying the relevant logs about the failures. Maybe you can look after this (check if failures are legitimate, fix if needed, restart travis job by closing/reopening this PR, etc.). Thanks.

**Comment by grosser** [comment]
fixed

**Comment by moolitayer** [comment]
@grosser please take a look [here](https://github.com/grosser/kubeclient/blob/0ad44c42742740a426fa8974803623c240fe2a91/lib/kubeclient/config.rb#L75) 

Looks really similar and probably should have the same exception

**Comment by grosser** [comment]
fixed

**Comment by simon3z** [comment]
@moolitayer can you review/ack?

**Pull request merged**
