### PR TITLE
make api_service method work

### PR DESCRIPTION
**Pull request by eatwithforks**
@cben  @moolitayer

### CODE REVIEW

**Comment by grosser** [comment]
I'd say either major or we make both available and call it a patch.
Is there a planned major bump coming up that we can piggy back on?

**Comment by cben** [comment]
I'm working on making both old and new work...

**Comment by cben** [comment]
Rebased, still blocked on compatibility, working on it.
I'm going to first rewrite `parse_definition` and add more tests in separate PR and then return to this...

**Comment by cben** [comment]
reminder to self: there will never be a perfect time but fixing this sooner is better.
I should merge this and bump major version sometime soon...

**Comment by cben** [comment]
Oh, wow.  Sorry for holding this up so long.
I'm planning a major version bump soon, see #435

**Pull request merged**
