### PR TITLE
Fixes #77: Use cert & key for SSL opts as detailed at http://apidock.com/ruby/v1_9_3_392/Net/HTTP/start/class#docs_body

### LINKED ISSUE #77: Wrong options for watch & SSL
From the docs on `net::http.start` (http://apidock.com/ruby/v1_9_3_392/Net/HTTP/start/class#docs_body):

    opt sets following values by its accessor. The keys are ca_file, ca_path, cert, cert_store, ciphers, close_on_empty_response, key, open_timeout, read_timeout, ssl_timeout, ssl_version, use_ssl, verify_callback, verify_depth and verify_mode.

Currently options set for cert & key are wrong (https://github.com/abonas/kubeclient/blob/master/lib/kubeclient/common.rb#L94-L101):

```
options = {
          use_ssl: uri.scheme == 'https',
          ca_file: @ssl_options[:ca_file],
          # ruby Net::HTTP uses verify_mode instead of verify_ssl
          # http://ruby-doc.org/stdlib-1.9.3/libdoc/net/http/rdoc/Net/HTTP.html
          verify_mode: @ssl_options[:verify_ssl],
          client_cert: @ssl_options[:client_cert],
          client_key: @ssl_options[:client_key]
        }
```

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by simon3z** [comment]
:+1:

**Comment by abonas** [comment]
LGTM
Thanks @jimmidyson !
Can you please elaborate how/in which project do you use kubeclient?

**Comment by jimmidyson** [comment]
@abonas Thanks for merging! Using it in fluentd plugin at https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/ to add Kubernetes metadata to container logs. This is hopefully being used in Kubernetes to provide logging cluster addon, WIP.

**Comment by abonas** [comment]
> This is hopefully being used in Kubernetes to provide logging cluster addon, WIP.

@jimmidyson , this is very interesting. can you elaborate more on the logging cluster addon part? who is working on that/what is the planned functionality?

**Comment by jimmidyson** [comment]
There are some initial docs at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/logging.md. I'm working on it as we've had centralised logging working in fabric8 for a while now & it's worth contributing. It's also going to be tech preview for openshift release I believe. I'm using this ruby client to enrich the logs with kubernetes metadata to make it easier to filter & provide authz too.

**Comment by abonas** [comment]
> There are some initial docs at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/logging.md. I'm working on it as we've had centralised logging working in fabric8 for a while now & it's worth contributing. It's also going to be tech preview for openshift release I believe. I'm using this ruby client to enrich the logs with kubernetes metadata to make it easier to filter & provide authz too.

thanks @jimmidyson , yes I understood the enrichment part the plugin was doing, but didn't know the details regarding the centralized logging work.

**Pull request merged**
